networks:
  displayrr:
    driver: bridge

services:
  switchrr:
    build: ./switchrr
    restart: unless-stopped
    networks:
      - displayrr
    ports:
      - "5556:5556"
    env_file: .env

  boardrr:
    build: ./boardrr
    restart: unless-stopped
    networks:
      - displayrr
    env_file: .env
    environment:
      OUTPUT_MODE: zmq
      MODE_NAME: uk_tdd
      SWITCHRR_FRAME_ADDRESS: tcp://switchrr:5600
      SWITCHRR_EVENT_ADDRESS: tcp://switchrr:5557
    volumes:
      - ./boardrr/config.json:/app/config.json:ro
      - ./boardrr/state.json:/app/state.json

  powrr:
    build: ./powrr
    restart: unless-stopped
    networks:
      - displayrr
    env_file: .env
    environment:
      MODE_NAME: powrr
      SWITCHRR_FRAME_ADDRESS: tcp://switchrr:5601
      SWITCHRR_EVENT_ADDRESS: tcp://switchrr:5557

  issrr:
    build: ./issrr
    restart: unless-stopped
    networks:
      - displayrr
    env_file: .env
    environment:
      MODE_NAME: issrr
      SWITCHRR_FRAME_ADDRESS: tcp://switchrr:5602
      SWITCHRR_EVENT_ADDRESS: tcp://switchrr:5557
